spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/snake_db
    username: Atakan
    password: Yalcin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
