 #spring:
   #datasource:
     #url: jdbc:postgresql://localhost:5432/snake_db1
     #username: Atakan
     #password: Yalcin
    # driver-class-name: org.postgresql.Driver

   #jpa:
     #hibernate:
    #   ddl-auto: update
   #  show-sql: true
  #   properties:
 #      hibernate:
 #        dialect: org.hibernate.dialect.PostgreSQLDialect
